// Generated by CoffeeScript 1.3.3
(function() {
  var run_tests;

  run_tests = function() {
    var logger;
    logger = new Logger("Foo");
    logger.error(1, 2, "hello", [1, 2]);
    logger.warn([1, 2], 3, "foo");
    logger.info("hello", "world");
    logger.debug({
      foo: 1,
      bar: 2
    }, "logger");
    return logger.trace(1, 2, 3);
  };

}).call(this);
